# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate Multitaper Adaptive Weights
#' 
#' @description Used to calculate the adaptive weights on eigenspectra using a bound on the 
#' broadband bias.
#' 
#' @param eigenSpec A \code{matrix} with columns containing the eigenspectra
#' @param ev A \code{vector} with the eigenvalues of the Slepian tapers.
#' @param k A \code{numeric} integer representing the number of tapers to use.
#' @param nFFT A \code{numeric} integer representing the total number of frequency bins 
#' that were used to estimate the spectra.
#' 
#' @details When estimating the variance, this function will overestimate because 
#' it includes the zero and nyquist frequency twice (should only be once).
#' 
#' @return A \code{matrix} containing the weights for each eigenspectra at each 
#' frequency.
adaptiveWeightsCpp <- function(eigenSpec, ev, k, nFFT) {
    .Call('transfer_adaptiveWeightsCpp', PACKAGE = 'transfer', eigenSpec, ev, k, nFFT)
}

absCplx <- function(x) {
    .Call('transfer_absCplx', PACKAGE = 'transfer', x)
}

coherencyOffsetCpp <- function(ykx, yky, dx, dy, nTaper, nFreqRange, nOffset, range2Start, freqRangeIdx, forwardCoh) {
    .Call('transfer_coherencyOffsetCpp', PACKAGE = 'transfer', ykx, yky, dx, dy, nTaper, nFreqRange, nOffset, range2Start, freqRangeIdx, forwardCoh)
}

#' The Title! Hello World
#' 
#' The description
#' 
#' @param x Something about a parameter
#' @return Nothing.
#' @details Some details about this function.
#' @export
rcpp_hello_world <- function() {
    .Call('transfer_rcpp_hello_world', PACKAGE = 'transfer')
}

sftCpp <- function(x, f, time) {
    .Call('transfer_sftCpp', PACKAGE = 'transfer', x, f, time)
}

olsTfEigen <- function(x, y, freqIdx, fOffsetIdxLst) {
    .Call('transfer_olsTfEigen', PACKAGE = 'transfer', x, y, freqIdx, fOffsetIdxLst)
}

olsTf <- function(x, y, time, n, npredictor, ntaper, freq, fOffset) {
    .Call('transfer_olsTf', PACKAGE = 'transfer', x, y, time, n, npredictor, ntaper, freq, fOffset)
}

